### ISSUE TITLE
0.2.0: Create Brupop Helm Chart

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-update-operator#126]
**Issue or Feature Request:**
Brupop should be installable via Helm. This would provide customers an easy route to install dependencies, like [cert-manager](https://cert-manager.io/) for managing SSL certificates used for communication with the apiserver, or the OpenTelemetry Collector, should we integrate with that rather than direct Prometheus integration.

**Comment by cbgbt** [comment]
We want to do this, but for now we're planning to update the project with installation instructions for cert-manager and Brupop. We will revisit Helm support in the future.

**Comment by KeenanLawrence** [comment]
I think this is worth looking into.
In our use case, we have various groups of nodes that we taint accordingly to control which workloads can run on them. An example would be a `core` node group that we run components we feel are cluster critical (autoscaler, loadbalancer, bruop controller and apiserver, descheduler, termination handler, etc). We'd like to specify tolerations and nodeSelectors for controller and apiserver, and also an `Exists` toleration for the agent so that it runs on all nodes.

At the moment, we painstakingly take the raw YAML and convert it into a Helm chart.

**Comment by stormmore** [comment]
As part of our deployment, we have had to make significant modifications to the apiserver deployment ranging from setting hostnetwork to true to adding tolerations and nodeSelectors, as well as adding tolerations to the agent daemonset
