### ISSUE TITLE
Set log format to plain

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#29]
**Image I'm using:**

`328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-update-operator:v0.1.2`

**Issue or Feature Request:**

The agent logs are written out with ansi control sequences because a PTY is attached for the agent pod (which is configured to have a TTY). This causes the logging library to select and use its richer user-oriented logging format - including, among other settings, colorized output by way of ansi control sequences. The output of the controller pod, which doesn't have a TTY configured, is plainly printed and friendlier to handle when debugging.

The agent should use the same plain output that the process in the controller's pod selects. Both processes should use an explicitly configured printing format to avoid subtle differences that may influence which format is chosen.

**Comment by cbgbt** [comment]
We've since changed the implementation of the operator pretty substantially, so this is no longer specifically relevant; however, we do have an issue open to move the logs from a [JSON-based format](https://github.com/trentm/node-bunyan) to a plain text-based one (#148).

I'll close this issue in favor of that one.
