### ISSUE TITLE
Can brs update operator update the kubelet version to a newer version?

### ISSUE THREAD

**Issue by takhat** [bottlerocket-os/bottlerocket-update-operator#465]
**Issue or Feature Request:**

We have bottlerocket update operator running on our EKS cluster, and our cluster is running on version v1.23. We upgraded EKS cluster to v1.24. We expected that the bottlerocket operator will upgrade the kubelet version on our worker nodes from 1.23 to 1.24. But it didn't happen.

We were wondering if the bottlerocket update operator will only upgrade bottlerocket OS or will it upgrade the Kubelet version as well. 

Thanks for your help!

**Comment by stmcginnis** [comment]
Hi @takhat - thanks for the good question. Individual components of Bottlerocket cannot be upgraded. The Bottlerocket upgrade process is image based, where the update operator helps identify that a new version is available and manages the upgrade process to switch over to the newer image.

Bottlerocket can only be upgraded to new versions of its own [variant](https://github.com/bottlerocket-os/bottlerocket#variants). Since the kubelet 1.24 version is a different variant (aws-k8s-1.24 vs aws-k8s-1.23) there is no upgrade path to migrate a particular instance from one variant to another, only one version of a variant to a newer version of the same variant.

There are actually two "upgrade" methodologies with Bottlerocket: in-place upgrades, and node replacement. Bottlerocket update operator helps manage the in-place upgrade, but you can also get to newer versions by adding completely new nodes to your cluster, cordoning off the old nodes and waiting for any workloads to drain from them, then deleting those old nodes. This migration method has the advantage that you _can_ go from one variant to another, since it doesn't need to update an existing instance to do it.

You can manually perform that migration upgrade path as described above, but you may want to consider EKS [managed node groups](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html). With managed node groups, it recognizes if there is a newer version and handles all of the cordoning and coordination to get the nodes upgraded without disrupting workloads.

**Comment by webern** [comment]
If this is a feature you would like to see, the bulk of the work would take place in Bottlerocket. See this very old issue and request that it be re-opened if you need this feature.

https://github.com/bottlerocket-os/bottlerocket/issues/1261

**Comment by takhat** [comment]
> 
Thanks for your response @stmcginnis 
Do you plan on adding this feature in future releases? If so, when can we expect to have this available?

**Comment by stmcginnis** [comment]
No plans right now, but see @webern's comment if you would like to see in-place variant migration.

**Comment by stmcginnis** [comment]
I _think_ the question has been answered, so I'm going to close this issue. If there are any other questions, or if there is any more to this, please feel free to reopen or file a new issue.
