### ISSUE TITLE
pod-based constraints (blocking-pod-selector)

### ISSUE THREAD

**Issue by vranystepan** [bottlerocket-os/bottlerocket-update-operator#64]
**Issue or Feature Request:**
Hello, is it possible to *block* reboot of a node in case there's running a workload with certain labels?

A good example is https://github.com/weaveworks/kured, this tool has a flag `--blocking-pod-selector` that postpones reboot of a node until it has no pods with the specified labels scheduled.

This feature would be great to prevent restarting of expensive tasks. 

Thanks in advance!

**Comment by vranystepan** [comment]
Is this block the right part for such functionality? https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/pkg/controller/manager.go#L198

**Comment by srgothi92** [comment]
Thanks for creating the issue! 

Currently, there is no way to block reboot of a node with arbitrary labels. However, the Bottlerocket update operator uses label `bottlerocket.aws/updater-interface-version` to determine the nodes to manage for updates. If you do not add this label to the nodes you would like to prevent reboot, it will be ignored by update operator and indirectly prevent the reboot. After the critical workload is complete and node can be updated, you can add the label `bottlerocket.aws/updater-interface-version` to consider for update.

Additionally, Kubernetes supports [pod disruption budgets](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets). Have you thought about using this mechanism instead? Our operator should respect any pod disruption budget since it calls the drain API, but we’ll need to verify this.


> Is this block the right part for such functionality? https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/pkg/controller/manager.go#L198


The code in the link above deals with errors occurring during node draining. Kubernetes provides different  configuration options for draining node, details can be found [here](https://pkg.go.dev/k8s.io/kubectl/pkg/drain#Helper) and [here](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain). Currently, we do not use force drain. Therefore, according to docs [here](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain), any workloads not managed by `ReplicationController`, `ReplicaSet`, `Job`, `DaemonSet` or `StatefulSet` would result in drain error and node will not be updated. So if your expensive workloads aren’t already part of one of these categories, the operator will skip those nodes.

With all that said, we would love to work with the community for a better update operator so we’ll keep this as a feature request (and are happy to work with you on implementation if you’d like). Also, I’d love to know more about your use-case so we can find a solution.

**Comment by cbgbt** [comment]
Just doing some backlog grooming. Currently, we suggest supporting this with [PodDisruptionBudgets](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets) as @srgothi92 mentioned.

Feel free to comment on this issue if you have a use-case that would prefer a label-based system, and we'll keep this issue around to track the idea!

**Comment by cbgbt** [comment]
Circling back to this as it's been a while. I think PodDisruptionBudgets captures this use-case. I'll close this issue, but happy to hear use-cases that we're missing if anyone wishes to re-open.
